---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars/main.yaml
  tasks:
    - name: "Template Client Config"
      template: src="etc/openvpn/client.ovpn.j2" dest="dist/client.ovpn" mode="0644"

    - name: "Tar a client config up"
      shell: >
        tar -pczvf client.tar.gz client.ovpn easyrsa/pki/ca.crt easyrsa/pki/issued/client.crt easyrsa/pki/private/client.key easyrsa/pki/private/ta.key
      args:
        creates: dist/client.tar.gz
        chdir: dist/

    - name: "Download the client config"
      fetch: src="dist/client.tar.gz" dest="~/Downloads/"
